### ISSUE TITLE
Outdate

### ISSUE THREAD

**Issue by franlinux** [KaOS-Community-Packages/wordpress-desktop#1]
Outdate

**Comment by demmm** [comment]
Anyone can work in KCP, instead of opening issues, why not help here?  Update this package if you found there is new version.

**Comment by franlinux** [comment]
Sorry, but I can not do it.

> On Mar 6 2016, at 10:21 am, demmm &lt;notifications@github.com&gt; wrote:  

>

> Anyone can work in KCP, instead of opening issues, why not help here? Update
this package if you found there is new version.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/KaOS-
Community-Packages/wordpress-desktop/issues/1#issuecomment-192887396).![](http
s://github.com/notifications/beacon/AQnz0wC7OibrUjnOwkQy4_jWc06tNtzvks5pqtToga
JpZM4HqQIN.gif)
